### ISSUE TITLE
5.1 support?

### ISSUE THREAD

**Issue by nicekiwi** [backup-manager/laravel-4#1]

**Comment by ShawnMcCool** [comment]
I don't know. I'm in the process of setting up a Laravel 5 project to test. But, balancing a few time sinks at the moment. Any reason to think that 5.1 doesn't work?

**Comment by bberlijn** [comment]
backup-manager/backup-manager requires aws/aws-sdk-php v2
https://github.com/backup-manager/backup-manager/blob/master/composer.json#L19

while laravel 5.1 requires aws/aws-sdk-php v3
https://github.com/thephpleague/flysystem-aws-s3-v3/blob/master/composer.json#L14

**Comment by ShawnMcCool** [comment]
@bberlijn awesome, could you possibly submit a pull request with that change? Otherwise, will get to it as soon as I get a chance.

**Comment by ShawnMcCool** [comment]
I'm closing this, recent merges have theoretically fixed 5.1 problems. I'm gongi to update the aws sdk dependency as mentioned by @bberlijn. Thanks everyone.

**Comment by nicekiwi** [comment]
Awesome :)

**Comment by orrd** [comment]
Is there currently a way to install flysystem-aws-s3-v3 with backup-manager?  Adding both "league/flysystem-aws-s3-v3": "~1.0" and "backup-manager/laravel": "~1.0" to my composer.json results in composer hanging indefinitely.
