### ISSUE TITLE
Rotating backups?

### ISSUE THREAD

**Issue by mikerogne** [backup-manager/laravel-4#10]
I imagine this probably isn't the ideal area to ask, (forgive me)... is there any current (or planned) functionality to support rotating backups? IE: If I only want twice daily backups, for a month's supply at any given time... is this possible currently?

IE: I want twice daily backups for the most recent 30 days.

Just wondering. I can manually delete older backups if need be.

**Comment by ShawnMcCool** [comment]
We would like to add this. But, our next 'release' will more or less feature better organization for the package as a whole and probably no new features.

**Comment by mikerogne** [comment]
Cool, cool.
