### ISSUE TITLE
Nothing happens in production on server

### ISSUE THREAD

**Issue by giovanniciriello** [backup-manager/laravel-4#100]
After installation and configuration with dropbox, all works in local.
But if I execute the test command
`php artisan db:backup --database=mysql --destination=dropbox --destinationPath=test.sql --compression=null`
it returns me:
```
Dumping database and uploading...

Successfully dumped mysql, compressed with null and store it to dropbox at test.sql
```
But no file is created (instead of run this command in local)

How can I debug this? What could be the problem?

**Comment by nafiesl** [comment]
Are you using dropbox API v2?
How about local storage destination (`--destination=local`)? Is backup file created?

**Comment by giovanniciriello** [comment]
@nafiesl I'm using of course API v2.
If I set destination to **local**, it correctly works also on my server.

**Comment by giovanniciriello** [comment]
I solved with `php artisan config:clear`

**Comment by wilsonwg** [comment]
I just wanted to make another quick note: when the destination is set to local, ex: db:backup --database=mysql --destination=local --destinationPath=test.sql --compression=null, the file is saved in the project_folder/storage/app directoy. It took me a while to find the saved file.
