### ISSUE TITLE
Lumen 5.5 Support

### ISSUE THREAD

**Issue by scottybo** [backup-manager/laravel-4#109]
In Lumen I'm getting the error:

```
In Laravel5DbBackupCommand.php line 9:
                                                                               
  Declaration of BackupManager\Laravel\Laravel51Compatibility::table(array $h  
  eaders, $rows, $style = 'default') should be compatible with Illuminate\Con  
  sole\Command::table($headers, $rows, $tableStyle = 'default', array $column  
  Styles = Array)     
```

And for obvious reasons... in `bootstrap/app.php` the following is registered

`$app->register(BackupManager\Laravel\LumenServiceProvider::class);`

And this class loads

`BackupManager\Laravel\Laravel51Compatibility`

When it needs to load

`BackupManager\Laravel\Laravel55Compatibility`

Are there any plans to add this pull request any time soon and add it as a release? https://github.com/backup-manager/laravel/pull/108

**Comment by vitorsdcs** [comment]
+1

**Comment by scottybo** [comment]
@vitorsdcs this has been done, just a heads up :)
