### ISSUE TITLE
[ErrorException]   Declaration of BackupManager\Laravel\Laravel5Compatibility::table()

### ISSUE THREAD

**Issue by Kryptonit3-zz** [backup-manager/laravel-4#11]
```
[ErrorException]
  Declaration of BackupManager\Laravel\Laravel5Compatibility::table() should
  be compatible with Illuminate\Console\Command::table(array $headers, array
  $rows, $style = 'default')
```

Laravel version: Laravel Framework version 5.0.33

I intend on upgrading soon. Any work around?

**Comment by laurentvd** [comment]
There is a _workaround_. Open the file `Laravel5Compatibility.php` in `vendor/backup-manager/laravel/src/` and replace `public function table(array $headers, $rows, $style = 'default') {` with `public function table(array $headers, array $rows, $style = 'default') {`. Do note that this is only a temporary fix.

**Comment by arall** [comment]
Still without an official fix for this issue?

**Comment by mojbenzcar** [comment]
is there any way that i can fix this issue in laravel 5.0.\* without the workaround suggested above?

**Comment by interludic** [comment]
I only get this issue from within vagrant, it seems ok on the vps.

**Comment by microdesign** [comment]
We must change code in core files of the package  !!!

**Comment by JoelGross** [comment]
I also am having this issue and can't use this package if we have to change core files in the package...

**Comment by pboiseau** [comment]
I have the same problem in Laravel 5.0.\* The laurentvd's solution works but any fix are coming ?

**Comment by ShawnMcCool** [comment]
The fix is to essentially have a driver for Laravel 4, Laravel 5.0-5.1, and Laravel 5.2+. We support 4 and 5.2+ but 5.0-5.1 driver has not been built. I keep trying to find the time... It's essentially the same as 5.2 minus the signature change mentioned above. I'll go ahead and make it.. But, it's going to be kind of ugly. That said, it should work without trouble.

**Comment by ShawnMcCool** [comment]
Hello, I have solved this. Provided in the newest version are Laravel 5.0 and Laravel 5.1+ service providers.
