### ISSUE TITLE
Fatal error: Call to undefined method Illuminate\Foundation\Application::configure()

### ISSUE THREAD

**Issue by sozokiamk** [backup-manager/laravel-4#112]
Fatal error: Call to undefined method Illuminate\Foundation\Application::configure()

**Comment by ShawnMcCool** [comment]
Please include information such as your Laravel version, the backup manager laravel version number you're using, and any other information that could allow someone to begin helping with this.

**Comment by sozokiamk** [comment]
laravel 5.3
