### ISSUE TITLE
maximum statement execution time exceeded

### ISSUE THREAD

**Issue by ahren-condos-ca** [backup-manager/laravel-4#114]
Getting this Error:
mysqldump: Error 3024: Query execution was interrupted, maximum statement execution time exceeded when dumping table `address_lookups` at row: 6006725

This is on a large table with 10million + rows. 

My my.cnf currently has:
max_execution_time=90000

So i ideally don't want to increase this as it will affect my entire site.
Hoping there is a way to increase this value only for this backup process. For instance if there could be a value in the config/backup-manager.php where I could set what the value should be for the backup manager which could then call something like 

\DB::statement("SET `max_execution_time`= ".config("backup-manager.max_execution_time"));

**Comment by HiradRoshandel** [comment]
Having the same problem. Any idea how this can be resolved?

**Comment by mustfirst** [comment]
Ran into the same issue. any ideas?

**Comment by ShawnMcCool** [comment]
This is definitely a database issue and is unrelated to this package. However I do empathize with you and hope that you find a solution.
