### ISSUE TITLE
MongoDB

### ISSUE THREAD

**Issue by peshkov3** [backup-manager/laravel-4#18]
When you use MYSQL DB everithing work fine, but sometimes we use MYSQL and MongoDB together. 
Are you planning to  automate MongoDB dumps in you package?

**Comment by ShawnMcCool** [comment]
I wouldn't be against the concept in general. However, I have no experience with Mongo.

**Comment by peshkov3** [comment]
Ok I will try to create mongo implementation. How can I contact you if it would be questions?

**Comment by ShawnMcCool** [comment]
Please feel free to do so. =)
