### ISSUE TITLE
Nothing to publish.

### ISSUE THREAD

**Issue by interludic** [backup-manager/laravel-4#19]
php artisan vendor:publish --provider="BackupManager\Laravel\Laravel5ServiceProvider"

returns 

Nothing to publish.

commands ARE NOT available db:backup, db:restore and db:list.

**Comment by ShawnMcCool** [comment]
Hi, what version of Laravel are you using? (2 months later, assuming you still are around)

**Comment by ShawnMcCool** [comment]
I am seeing this in Laravel 5.2.

**Comment by interludic** [comment]
I am frequently 'composer update' ing,  so i would say it was 5.1 but now 5.2
