### ISSUE TITLE
Issues with Laravel 5.1

### ISSUE THREAD

**Issue by rodrigore** [backup-manager/laravel-4#2]
Hi, I'm testing this package with Laravel 5.1 and I found a few trouble in order to make it work.

After to install the package and run **php artisan** the console throw an  _failed to open stream_.

```
vendor/backup-manager/laravel/src/../../../config/backup-manager.php): failed to open stream: No such file or directory'
```

To fix that I change the line where the variable $configPath is set. The actual method is : 

```
        $configPath = __DIR__ . '/../../../config';
```

and I changed to the helper method of laravel: **config_path()**, which is more clean, short and reliable.

After that, when I run **php artisan** again, the console say:

```
  [ReflectionException]
  Class BackupManager\Integrations\Laravel\DbBackupCommand does not exist
```

So I noticed that in https://github.com/backup-manager/laravel/blob/master/src/Laravel5BackupManagerServiceProvider.php#L109-L111  the namespace is BackupManager\Integrations, where Integration doesn't exist.  To fix that, I removed the Integrations word like this:

```
        'BackupManager\Laravel\DbBackupCommand',
        'BackupManager\Laravel\DbRestoreCommand',
        'BackupManager\Laravel\DbListCommand',
```

And if I run **php artisan** another error is display:

```
[ErrorException]
  Declaration of BackupManager\Laravel\BaseCommand::table() should be compatible with Illuminate\Console\Command::table(array $headers, $rows, $style = 'default')
```

To fix that, is necessary to remove the typehinting array in the $rows variable https://github.com/backup-manager/laravel/blob/master/src/BaseCommand.php#L38 , like this:

```
    public function table(array $headers, $rows, $style = 'default') 

```

And now I can run **php artisan** without problem in Laravel 5.1 :smile:  (but i'm actually in this step, i will try to use this package with s3, and I hope that this fix the errors)

**Comment by ShawnMcCool** [comment]
Hi thanks a ton. Could you submit a pull request with those changes?

**Comment by rodrigore** [comment]
Done! I hope this will be OK ,because I don't know how can I test my fork version, but I made the same changes that  I did in your package.

**Comment by ShawnMcCool** [comment]
@rodrigore merge.

With that and another PR merge, I think we're good. We are making solid iterative improvements.

Thanks everyone.
