### ISSUE TITLE
Can not install league/flysystem-aws-s3-v3

### ISSUE THREAD

**Issue by jakeryansmith** [backup-manager/laravel-4#20]
I think the backup-manager/laravel is requiring aws-sdk v2 while league/flysystem-aws-s3-v3 requires aws-sdk v3. This prevents you from installing both.

**Comment by naimkhalifa** [comment]
Same problem for me.

**Comment by devinfd** [comment]
same

**Comment by duellsy** [comment]
Any progress on this?

**Comment by Elyahou** [comment]
+1

**Comment by ShawnMcCool** [comment]
I'm personally a bit distracted with some demanding projects at the moment. However, if someone here feels that they have a solid grasp of the problem, submits a pull request, and maybe someone else reasonably considers about and tests the fork and verifies that it is solid then we can get it in here.

**Comment by ShawnMcCool** [comment]
Ok, I released a new version that should solve this. Let me know what you see.
