### ISSUE TITLE
php artisan clear-compiled gives me "Unresolvable dependency resolving"

### ISSUE THREAD

**Issue by philippzentner** [backup-manager/laravel-4#21]
I use dependency injection in an artisan command. Like described here the constructor is capable of doing so: http://laravel.com/docs/5.1/artisan#writing-commands

This is the error i get when composer calls "php artisan clear-compiled":

```
 [Illuminate\Contracts\Container\BindingResolutionException]                                                         
  Unresolvable dependency resolving [Parameter #0 [ <required> array $config ]] in class BackupManager\Config\Config  
```

Edit:
I moved it into an own command and called it via command-bus. There the dependency-injection works fine and the deployment process runs through without any error.
So the library seems to have problems with the dependency injection in artisan commands OR the DI doesn't work properly in artisan commands and it is a Laravel issue. You may close this issues if this specific case should be ignored (should perhaps be documented then).

**Comment by ShawnMcCool** [comment]
The problem is that it's incompatible with Laravel 5.1 (I believe) do to the fact that theres' the 'array' type-hint. Something along those lines.

**Comment by ShawnMcCool** [comment]
Ok, I have released a new version of this package that has separate Laravel 5.0 and 5.1+ service providers. If this doesn't solve everything then let me know.
