### ISSUE TITLE
how can i set the time stamp  as the backup file name?

### ISSUE THREAD

**Issue by liucf** [backup-manager/laravel-4#22]
how can i set the time stamp  as the backup file name?

Or the backup file name can not be a dynamic name?

**Comment by kirschbaum** [comment]
@liucf Here is a quick solution using Laravel's built in scheduler:

``` php
    /**
     * Define the application's command schedule.
     *
     * @param  \Illuminate\Console\Scheduling\Schedule  $schedule
     * @return void
     */
    protected function schedule(Schedule $schedule)
    {
        $date = Carbon::now()->toW3cString();
        $environment = env('APP_ENV');
        $schedule->command("db:backup --database=mysql --destination=s3 --destinationPath=/{$environment}/projectname_{$environment}_{$date} --compression=gzip")->twiceDaily(13,21);
    }
```

There is a timestamp() method on Carbon if you prefer that format. And more on scheduling can be found here: http://laravel.com/docs/5.1/scheduling

**Comment by liucf** [comment]
@kirschbaum Thank you so much!!!!

**Comment by liucf** [comment]
@kirschbaum by the way, is there a way to email the back up file as attachment  to some email address?

**Comment by kirschbaum** [comment]
@liucf Not built into this package. Check out the 'backup-manager.php' config file for supported methods. If none of those work and you want to send an email it shouldn't be hard. Just have the backup manager save to your local disk and then use built-in Laravel mail functionality to send the email with attachment: http://laravel.com/docs/5.1/mail

**Comment by ShawnMcCool** [comment]
@kirschbaum thanks for the method. I'm going to add it to the documentation.
