### ISSUE TITLE
Dumping database and uploading...                                                           [League\Flysystem\FileExistsException] 

### ISSUE THREAD

**Issue by Houbsi** [backup-manager/laravel-4#23]
```
Dumping database and uploading...

  [League\Flysystem\FileExistsException]             
  File already exists at path: backup-production.gz
```

if i schedule it directly within forge, i get this warning. Isn't there a possibility to make an option to overwrite "older" files?

**Comment by Houbsi** [comment]
https://github.com/backup-manager/backup-manager/issues/65 takes it on

**Comment by ShawnMcCool** [comment]
The backup manager is extremely extensible. Just create a new procedure that checks / removes the file before uploading it. The BackupManager class itself can be replaced with your own bootstrapping class that builds up the manager with the procedures that you'd like.
