### ISSUE TITLE
How to Overwrite to an existing backup ?

### ISSUE THREAD

**Issue by Ham3D** [backup-manager/laravel-4#24]
is there any option to Overwrite existing backup and update it?
i tried it with dropbox , it throw exception: File already exists at path:

**Comment by ShawnMcCool** [comment]
You might consider making a new procedure that does this. Then just do something like this

``` PHP
        return new Whatever\NewBackupProcedure(
            $this->filesystems,
            $this->databases,
            $this->compressors,
            $this->getShellProcessor()
        );
```

**Comment by barryvdh** [comment]
Would it be possible to create a flag for this? Eg. `--overwrite`.

In the case of Amazon, it's quite common to setup backup-policies there, right? Eg. keep backups for x-days, move old revisions out etc. Seems cleaner the a new file for each day.
