### ISSUE TITLE
[Question] new tag for PHP7

### ISSUE THREAD

**Issue by ninjaparade** [backup-manager/laravel-4#34]
Hey @ShawnMcCool,

I am currently using `1.0.*@dev` to get this package to install on PHP7 servers.

I saw that accepted a PR for the `composer.json` update. Were you planning on tagging or should I continue to use `@dev`?

Thanks for your time.

**Comment by rleger** [comment]
Same here, I get : 

backup-manager/laravel 1.0.2 requires php ^5.5.0 -> your PHP version (7.0.0-2+deb.sury.org~trusty+1) or "config.platform.php" value does not satisfy that requirement.

when installing on a server provisioned recently by forge

Thanks a lot for that great package !

**Comment by jellebreuer** [comment]
+1

**Comment by cmosguy** [comment]
Does anyone here feel like taking on a PR for this?

**Comment by vesper8** [comment]
+1

**Comment by ShawnMcCool** [comment]
Hi all, tagged 1.0.3. Let me know if all is well.

**Comment by cmosguy** [comment]
@ShawnMcCool thanks! I just tested this out and your tagged worked!  Thanks for the quick response, I think you can close this issue!

**Comment by ShawnMcCool** [comment]
success!

**Comment by ninjaparade** [comment]
@ShawnMcCool :+1: :100: :heart: :
