### ISSUE TITLE
Cant backup with postgreSQL

### ISSUE THREAD

**Issue by umarmw** [backup-manager/laravel-4#36]
When executing this command from Command line:

`php artisan db:backup --database=pgsql --destination=dropbox --destinationPath=2015-laravel5.sql --compression=null`

Dumping database and uploading...

  [BackupManager\ShellProcessing\ShellProcessFailed]
  'PGPASSWORD' is not recognized as an internal or external command,
  operable program or batch file.

Any idea?

**Comment by ShawnMcCool** [comment]
Hmm. Any idea what shell command it was trying to run?

**Comment by umarmw** [comment]
this one:
`PGPASSWORD=%s pg_dump --host=%s --port=%s --username=%s %s -f %s`

**Comment by ShawnMcCool** [comment]
Ah, are you not on Linux? What shell is the default?

**Comment by umarmw** [comment]
No, am unfortunately on Windows 10 and running Postgres (PostgreSQL) 8.4.22

Can you please guide me how to find the default shell?

**Comment by ShawnMcCool** [comment]
Ah, I see. This package doesn't really support Windows. It'd need at LEAST one custom task for backup up PostgreSQL databases in Windows.

Many people use Vagrant virtual machines to develop on windows. Laravel has the Homestead virtual machine environment that would allow you to develop on windows using Linux. It's rather effortless. Additionally, you won't need those weird Windows releases of software (WAMP, etc).

Basically, I'm sorry that you won't be able to use this tool in your current workflow. However, it is my personal opinion that you would gain many benefits by switching to a virtual development environment (only for your server software, not your coding software like PHPStorm or ST or whatever).

https://laravel.com/docs/master/homestead

Using Homestead (or another virtual environment like it) you could use this package with almost zero additional configuration or difficulty.

I'm going to close this issue. If you'd like to continue discussing it, you're welcome to continue responding here directly.
