### ISSUE TITLE
Not usable for Laravel 5.2

### ISSUE THREAD

**Issue by cre8** [backup-manager/laravel-4#37]
I installed a fresh 5.2 version and wanted to install the backup-manager.

But it requires symfony/process 2.\* but Laravel is shipped with 3.*

Is there any way to use it?

**Comment by ShawnMcCool** [comment]
Yea, this is a good point. I'll need to update and tag a new major version. I'm unfortunately out all day tomorrow. I can probably try to get this done on Monday. If you don't mind hitting me up again on Monday as a reminder, that couldn't hurt. ;)

**Comment by cre8** [comment]
_remind_

**Comment by ghost** [comment]
:+1:  please remind

**Comment by dexbarrett** [comment]
Reminder :+1:

**Comment by ShawnMcCool** [comment]
I haven't forgotten this btw. I've put two separate chunks of time into it. Very soon I'll have it completed. Just need to finish up some testing.

**Comment by ghost** [comment]
@ShawnMcCool fixed, thanks a lot!

**Comment by ShawnMcCool** [comment]
I think that the interactive dialogs don't work yet. But, actually interacting with the library should. More changes coming.

**Comment by jpmurray** [comment]
So for a fresh, clean install, I should wait @ShawnMcCool ? (I never installed the package, I was waiting for 5.2 support :P )

**Comment by ShawnMcCool** [comment]
There is a backup-manager/backup-manager package that is just a php library that will work anywhere. That can ALWAYS be used. The Laravel package really just tacks on a service provider (a few to deal with backwards compatibility breaks) and some artisan commands.

If you want the commands to work in 5.2, then it's not there yet. I need to figure out the new dialog helper stuff because it changed. I'm not sure how it even changed, yet.

But, the service provider and the actual library work. The library is completely tested and testable, where the Laravel package requires a separate install for every version and manual testing so development is slower.

**Comment by paceband** [comment]
reminder!

**Comment by ants-house** [comment]
+1

**Comment by Snaver** [comment]
Temporary work around is to implement 'manually' https://gist.github.com/Snaver/5c292cdeee95cee856b6. Example given for postgres DB to Dropbox.

**Comment by skcin7** [comment]
@ShawnMcCool , I reacted with a heart emoji to show appreciation for making this, and also to give a kind reminder to add support for Laravel 5.2. 👍  I know it's just a wrapper for the `backup-manager/backup-manager` package, but when people have things configured to work via command line, it makes a difference.

I managed to get Symfony command-line inputs working by using the pull request by @devonzara, here:
https://github.com/backup-manager/laravel/pull/44
I recommend checking this out and merging changes to the master branch if you see it fitting enough for this package.

Now commands like `php artisan db:restore` work great! However, things like auto-completion of fields in the command line presently do not work.

Thanks again for your work. -Nick

**Comment by ShawnMcCool** [comment]
I don't really have time to support various versions of the framework. If someone wants to jump in and manage this repo, I appreciate it. Otherwise, I need pull requests if you want to make a change. I have too much work to make supporting 5.2 a reasonable goal.
