### ISSUE TITLE
not such LumenServiceProvider

### ISSUE THREAD

**Issue by dayukiller** [backup-manager/laravel-4#38]
hi, I use Lumen framework and wanna use backup-manager to backup my database;
but after I run 'composer require backup-manager/laravel',
there is no such providers named 'LumenServiceProvider'.
how could I fix this?thank you !

**Comment by ShawnMcCool** [comment]
Hello, Lumen is an untagged release. Try dev-master. There's a new version coming soon.

**Comment by dayukiller** [comment]
It works! 
Thank you!
