### ISSUE TITLE
i m facing some problem

### ISSUE THREAD

**Issue by ghost** [backup-manager/laravel-4#40]
i install this package successfully
in my server my cron is= \* \* \* \* \* php /path/to/artisan schedule:run

in my schedule here is the code

 $schedule->command(
        "db:backup --database=mysql --destination=dropbox --destinationPath=`date +\%Y/%d-%m-%Y` --compression=gzip"
        )->everyTenMinutes();

but fact is its backup the database only once in a day?
but i put every ten minutes. can you tell me why i face this problem?

**Comment by ghost** [comment]
Now i see its backup in every ten minutes in storage/app folder not uploading in dropbox . Only backup the db in dropbox once a day? Can you tell me the fact plz? I m waiting

**Comment by ShawnMcCool** [comment]
I suggest looking at your log and trying to figure out what's going on. Or modify the code and step through it. Or put some debug messages that write to the log.

The backup-manager's source code is extremely small and you should be able to figure out what's going on without too much trouble.

**Comment by ghost** [comment]
Okey bro. I will try and let you know. Thanks for replay
