### ISSUE TITLE
save backup to local project backup folder 

### ISSUE THREAD

**Issue by mohamedsharaf** [backup-manager/laravel-4#41]
can this happen i dont need s3 or dropbox just local backupfolder

**Comment by freel132** [comment]
yes you can. 
tested working perfect.

If you will need help, let me know.

**Comment by mitchellvanw** [comment]
Hi @mohamedsharaf, you can either use the required `local` named connection or, if you want your backups in a path, you could create a new connection with the type `Local`:

``` php
'local_backups' => [
    'type' => 'Local',
    'root' => storage_path('backups'),
],
```

Hope this helps

**Comment by mohamedsharaf** [comment]
will try thanks really appreciated
