### ISSUE TITLE
Laravel 5.2 - The helper "dialog" is not defined. 

### ISSUE THREAD

**Issue by dorukgunes** [backup-manager/laravel-4#42]
When i try to db:backup in my artisan console the following error occurs. I am using laravel 5.2.

[Symfony\Component\Console\Exception\InvalidArgumentException]  
  The helper "dialog" is not defined.

**Comment by dorukgunes** [comment]
Okay i see that you are developing integration for 5.2, closing the issue.

**Comment by skcin7** [comment]
But...... this didn't list a solution???
