### ISSUE TITLE
The helper "dialog" is not defined.

### ISSUE THREAD

**Issue by devonzara** [backup-manager/laravel-4#43]
I receive the following error when doing `db:list`, using the Laravel 5.1+ driver on Laravel 5.2.

> vagrant@homestead:~/Code/Acme$ php artisan db:list
> These arguments haven't been filled yet: source, path.
> The following questions will fill these in for you.
> 
> Available sources: local, s3, gcs, rackspace, dropbox, ftp, sftp
> 
>   [Symfony\Component\Console\Exception\InvalidArgumentException]  
>   The helper "dialog" is not defined.     

The Dialog Helper was depreciated in Symfony 2.5 and removed in 3.0, yet the package is configured to require `symfony/process` version `~2.1||~3.0`.

The same is true for the Table Helper.

**Comment by Anahkiasen** [comment]
Having the same issue here

**Comment by ants-house** [comment]
+1

**Comment by nakov0301** [comment]
+1

**Comment by ShawnMcCool** [comment]
@mitchellvanw does the new version you're working on releasing support 5.2?

**Comment by dhonions** [comment]
+1

**Comment by skcin7** [comment]
I am also having the same issue.
I've used backup-manager with absolutely no issues in Laravel 5.1. Now I'm in 5.2 and I continue to receive this InvalidArgumentException, with message "The helper "dialog" is not defined.". I'm not sure what to do about this at the moment, but I will continue to do research.

**Comment by epic-kaso** [comment]
The way around the issue is to provide all the options in the command line once. example is `php artisan db:restore --source local --sourcePath /neo/finance.sql.gz --database finance --compression gzip`

**Comment by setkyar** [comment]
I am also facing same issue.
