### ISSUE TITLE
Backup from dynamic connections outside database.php

### ISSUE THREAD

**Issue by digixweb** [backup-manager/laravel-4#63]
Any ideas how to setup backups for dynamic connections which credentials are stored in a mysql database. So in stead of getting the connection details from database.php I need a way to set these from my msql user table which stores all dynamic user connections.

**Comment by Garric15** [comment]
You can set the credentials just before calling the command.
```PHP
\Config::set('database.connections.dynamic.host', $host);
\Config::set('database.connections.dynamic.username', $username);
\Config::set('database.connections.dynamic.password', $password);

$schedule->command("db:backup --database=dynamic --destination=local --destinationPath=".date('Y-m-d')." --compression=gzip")->daily();
```
