### ISSUE TITLE
db:restore command not properly accepting input from command line? It asks the question twice?

### ISSUE THREAD

**Issue by skcin7** [backup-manager/laravel-4#70]
Ok, I'm getting a strange bug with the db:restore command. I've been using `backup-manager/laravel` for a while now with no issues, but I recently updated *something* (not sure what) which is causing the `db:restore` command to have a peculiar bug.

Here's an example of my terminal command line window:
```
$ php artisan db:restore
These arguments haven't been filled yet: source, sourcePath, database, compression
The following questions will fill these in for you.

Available storage services: local, s3, gcs, rackspace, dropbox, ftp, sftp
From which storage service do you want to choose?dropbox
From which storage service do you want to choose? dropbox

 From which path do you want to select? :
 > 
```

It asks "From which storage service do you want to choose?", so I type in 'dropbox' (the autocomplete is auto-filling in this answer) and I hit enter, but it seems to be rejecting this input, and asks the question again. I type 'dropbox' in again (this time autocomplete doesn't work) and it accepts the input, and moves onto the next question.

No idea why the first time it asks a question, where autocomplete is working properly, it is rejecting the input, but seems to accept the input properly the second time it asks a question, where autocomplete is _not_ working properly.

It does this for every question. This is especially frustrating because autocomplete does not work the 2nd time the question is asked, so I need to manually type in the long filenames of my SQL database dumps in order to successfully restore that dump.

I recently begin looking around in files associated with this package such as `DbRestoreCommand.php`, `AutoComplete.php`, and a few others but can't quite figure out what's causing the bug at the moment. I'll continue to look, but if anybody knows what's causing the bug and can point it out so it can be fixed, it would be greatly helpful and appreciated.

Thanks regardless for the amazing package which I use regularly.

**Comment by skcin7** [comment]
It appears that in `AutoComplete.php`, the first time the question is asked, the `useSymfontDialog` function is run, but the second time the question is asked, the `useSymfonyQuestion` function is run. It works properly the second time with the `useSymfonyQuestion` function. I am still debugging and figuring out why `useSymfontDialog` is called the first time.

**Comment by skcin7** [comment]
I managed to fix the bug by removing the try/catch/finally block in the `autocomplete` function in `AutoComplete.php`. I replaced that block of code with the following:

`return $this->useSymfontDialog($dialog, $list, $default, $validation);`

This is the same line that was inside the `try` block. I'm not quite sure what the point of thinking was of the try/catch/finally, but since I've changed it, it works fine now for me. If somebody can please comment on this with additional information or insight, it would be helpful.

**Comment by ShawnMcCool** [comment]
Hi @skcin7 you're welcome to submit a pull request. I'll merge it.
