### ISSUE TITLE
Scheduled backup - prompts

### ISSUE THREAD

**Issue by sunnyjayjay** [backup-manager/laravel-4#71]
I want to use this as a scheduled artisan command on Forge, to run nightly at 3am. But how do I override the prompts?

**Comment by ShawnMcCool** [comment]
I do this by providing all of the details on the command line in a bash script. What does your script look like?

**Comment by sunnyjayjay** [comment]
Thanks. I realise now it was a typo in my command line. All is now fine, thanks and sorry for bothering you.
