### ISSUE TITLE
restore from oneliner

### ISSUE THREAD

**Issue by digitalit** [backup-manager/laravel-4#74]
Hi,

php artisan db:backup --database=mysql --destination=dropbox --destinationPath=`date +\%Y/%d-%m-%Y` --compression=gzip 

does the backup but what if i want to build an restore function in php to trigger an artisan call.

I would like to be able to restore with one line is that possible?

Thank you.

**Comment by ShawnMcCool** [comment]
I think that it'd be a good idea to create a procedure that selected back a list of the backups in a folder, then selected the most recently stored one, then restored it.

**Comment by HiradRoshandel** [comment]
@ShawnMcCool I would like to know if thats possible too.
I can do it up until list of backups:

`php artisan db:restore --database=mysql  --compression=gzip --source=s3 --sourcePath={path}`
but I don't know how I can select the most recent backup programmaticaly

**Comment by ShawnMcCool** [comment]
Don't do this kind of thing with the Laravel integration. Do it here: https://github.com/backup-manager/backup-manager

Copy the RestoreProcedure class, create a RestoreMostRecentBackup class (or something) and do it in there.
