### ISSUE TITLE
Not fully compatible with Laravel 5.4

### ISSUE THREAD

**Issue by laurencei** [backup-manager/laravel-4#79]
The "dynamic" setting of timestamps in the example command makes this package partially incompatible with Laravel 5.4 and mutex's. i.e:

```
    $date = Carbon::now()->toW3cString();
    $schedule->command("db:backup --destinationPath=/{$date}")->twiceDaily(13,21);
```

Because the Laravel mutex uses the full command expression as part of the construction - it means you always get different mutexes running this command. 

For example - you'll get commands run as

```
db:backup --destinationPath=/2017-07-30T23:13:54+00:00 
db:backup --destinationPath=/2017-07-30T23:13:53+00:00 
```

This creates issues when using on load-balanced applications etc. Basically `->withoutOverlapping()` wont work here.

My ideas for a solution;
1. set timestamps as an option on the config of each filesystem driver
2. set timestamps as a flag option

I'm thinking 2 is best? You could do `--timestamp="Y-m-d"` or whatever format you want. That way the command itself is static, but the result is a dynamic timestamp that is appended to the filename.

If I did a PR on this - which option would you prefer?

**Comment by ShawnMcCool** [comment]
Can we have #2 and a sensible default?

**Comment by ShawnMcCool** [comment]
Thanks for the PR.
