### ISSUE TITLE
Incompatible method breaks on Laravel 5.0.33

### ISSUE THREAD

**Issue by alexgarrettsmith** [backup-manager/laravel-4#8]
On:

https://github.com/backup-manager/laravel/blob/master/src/Laravel5Compatibility.php

`$rows` is typecast as an array in Laravel 5.0.33, so this breaks.

I'm not sure if you're explicitly supporting 5.1+, or this is a mistake. In the docblock, it's showing an array typecast.

I would have PR'd, but just wanted to check this first.

**Comment by ShawnMcCool** [comment]
Oh FFS Laravel. =(

**Comment by chargoy** [comment]
Hi! Do you know when this is going to work? :)

**Comment by ShawnMcCool** [comment]
I think that I have to separate the Laravel versions more to keep the repository sane, which in turn makes it a bit less sane. 

My current idea is to create a Symfony component and then have the Laravel components depend on the Symfony component and have a different version for Laravel4, Laravel 50, and Laravel 52.

I'd love any suggestions that you had to make this less nightmarish.

I was treating Laravel 5 as a single major version. But, it doesn't use semver apparently.

**Comment by ShawnMcCool** [comment]
I just tagged a new version that has Laravel 5.0 and Laravel 5.1+ service providers that solves this issue.

**Comment by webcrazy** [comment]
Hello I still got this.
laravel version : 5.0.34

```
[ErrorException]                                                                                                                                                                   
  Declaration of BackupManager\Laravel\Laravel50Compatibility::table() should be compatible with Illuminate\Console\Command::table(array $headers, array $rows, $style = 'default') 
```
