### ISSUE TITLE
Dropbox client not found

### ISSUE THREAD

**Issue by 4sh3** [backup-manager/laravel-4#83]
This package is not working for me:

composer require srmklive/flysystem-dropbox-v2

PHP Fatal error:  Class 'Dropbox\Client' not found in C:\xampp\htdocs\copytrade\copytrade\vendor\backup-manager\backup-manager\src\Filesystems\DropboxFilesystem.php on line 27

  [Symfony\Component\Debug\Exception\FatalErrorException]
  Class 'Dropbox\Client' not found

**Comment by kazemisoroush** [comment]
Try `league/flysystem-dropbox` instead of `srmklive/flysystem-dropbox-v2`. This solved my problem.

**Comment by kendepelchin** [comment]
This solved the problem until last thursday (28th of September) where dropdown retired the API v1 endpoint completely.
https://blogs.dropbox.com/developers/2016/06/api-v1-deprecated/

```September 28, 2017: API v1 endpoints are turned off.```

**Comment by hideyatsu** [comment]
any update with this?

**Comment by ShawnMcCool** [comment]
I don't use dropbox and am not sure what the ultimate solution should be. I would check the Flysystem (the multi-storage backend that we're using) repo to see what they're doing. 

If you drop the info here, someone will inevitably make a pull request that will be merged in. 

Every little bit helps.

**Comment by skcin7** [comment]
Anybody figure this out?

**Comment by jraddaoui** [comment]
This issue looks to be fixed in backup-manager after https://github.com/backup-manager/backup-manager/commit/d3f08d7aec10545861ffaced62d8691e0716d38d and https://github.com/backup-manager/backup-manager/commit/70506081f0757390cb49eeb7e62ff2dd84fb4eae

For now, forcing the dev. version of that package works for me:

`composer require backup-manager/backup-manager:1.0.x-dev`

**Comment by skcin7** [comment]
@jraddaoui Thank you. That works for me.

**Comment by tintnaingwin** [comment]
This issue fixed on version 1.3 . It need to change `Dropbox` to `DropboxV2` at backup-manager.php .

**Comment by ShawnMcCool** [comment]
@tintnaingwinn can i close this issue?

**Comment by tintnaingwin** [comment]
@ShawnMcCool  yes, you can .

**Comment by ShawnMcCool** [comment]
Thank you.
