### ISSUE TITLE
Laravel 5.5 Support

### ISSUE THREAD

**Issue by dlwatersuk** [backup-manager/laravel-4#86]
```php
 [ErrorException]
  Declaration of BackupManager\Laravel\Laravel51Compatibility
::table(array $headers, $rows, $style = 'default') 
should be compatible with Illuminate\Console\Command
::table($headers, $rows, $style = 'default')
```

Getting this after updating from 5.4 to 5.5

**Comment by quelo83** [comment]
+1

**Comment by dlwatersuk** [comment]
Seems like this was the only thing blocking 5.5 from working: https://github.com/backup-manager/laravel/pull/89

**Comment by SergeyMiracle** [comment]
@dlwatersuk there is already a PR waiting 😄  [#87](https://github.com/backup-manager/laravel/pull/87)

**Comment by dlwatersuk** [comment]
Oops, way more thorough than my quick hack also! will close this
